---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - automation.demo.pb
  resources:
  - sensors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automation.demo.pb
  resources:
  - sensors/finalizers
  verbs:
  - update
- apiGroups:
  - automation.demo.pb
  resources:
  - sensors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - automation.demo.pb
  resources:
  - thermostats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automation.demo.pb
  resources:
  - thermostats/finalizers
  verbs:
  - update
- apiGroups:
  - automation.demo.pb
  resources:
  - thermostats/status
  verbs:
  - get
  - patch
  - update
