# permissions for end users to edit sensors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sensor-editor-role
rules:
- apiGroups:
  - automation.demo.pb
  resources:
  - sensors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automation.demo.pb
  resources:
  - sensors/status
  verbs:
  - get
