name: K3S test
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging'     
        required: false
        default: false
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2 
    - name: Prepare docker registry and k3s cluster
      run: |
        ./create-cluster-k3s.sh
        while [[ $(kubectl get nodes -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "Waiting for cluster nodes to be ready"; sleep 2; done
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1   
    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - 
      name: Cache go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ./bin
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Unit tests
      run: |
        make test

    - name: Generate and install manifests
      run: |
        make manifests
        make install 
    -
      name: Docker build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.actor }}/thermostat:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy controller
      run: |
        make deploy IMG=ghcr.io/${{ github.actor }}/thermostat:latest
        while [[ $(kubectl get deployment -n thermostat-system kymactl-controller-manager -o 'jsonpath={..status.availableReplicas}') != 1 ]]; do echo "Waiting for thermostat controller to be available"; sleep 2; done

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

